###
GET http://localhost:3000/specialities


###
GET http://localhost:3000/specialities/5ebc9f8bead90c2e47ba76d5


###
POST http://localhost:3000/specialities
Content-Type: application/json

{
    "name": "Adolescent Medicine",
    "createdBy": 79027,
    "updatedBy": 49305
}

###
PATCH http://localhost:3000/specialities/5ebc9ff86ea8d12e93b73248
Content-Type: application/json

{
    "name": "Medicine 1",
    "createdBy": 79027,
    "updatedBy": 49305
}


###
DELETE http://localhost:3000/specialities/5ebc9f81ead90c2e47ba76d4


###
GET http://localhost:3000/providers

###
GET http://localhost:3000/providers/59c19cba5754f2d72b65c687

###
POST http://localhost:3000/providers
Content-Type: application/json

{
    "status": "READY_FOR_REVIEW",
    "firstName": "Wilfrido",
    "lastName": "Bonett",
    "middleName": "Y",
    "email": "wil@gmail.com",
    "specialty": "59c19c6e5754f2d72b65c662",
    "projectedStartDate": "2017-06-23",
    "employerId": 318,
    "providerType": "NP",
    "staffStatus": "COURTESY",
    "assignedTo": null,
    "createdBy": 47648,
    "updatedBy": 43545,
    "photo": null
  }


###
DELETE http://localhost:3000/providers/59c19cba5754f2d72b65c690



